[package]
name = "udmx"
version = "0.0.1"
edition = "2024"
description = "USB DMX interface library for Anyma uDMX."
authors = ["milan <milan@milan.wtf>"]
license = "MIT"

[dependencies]
rusb = "0.9"
thiserror = "1.0"
log = "0.4"

[dev-dependencies]
pretty_env_logger = "0.5.0"
ctrlc = "3.4.7"
